### ISSUE TITLE
HipChat plugin

### ISSUE THREAD

**Issue by lalyos** [progrium/docker-plugins#1]
Hi Jeff,

I've created a HipChat plugin: https://github.com/lalyos/docker-plugin-hipchat . What is your preference on maintaining available plugins?
- maintaining a list in `contrib/PLUGINS.md` or similar
- sending PR against the `plugins/available` subdir

**Comment by lalyos** [comment]
btw I find the decomposition the functionality into several projects (basher/plugn/dockerhook) superb. Its hard to get the unix philosophy correctly implemented:

> do one thing and do it well

Its a similar feeling like at the probability theory class. You hear 'its obvious' , than you think about it a couple of hours, and then it seems 'obvious'

**Comment by progrium** [comment]
This is great, thank you. You can submit a PR to add to available, just make sure to add your info in the plugin.toml and you'll have to join as a co-maintainer. Also love it if you keep the readme.md. Otherwise, I'd take a simple file for a list of known third party plugins.
